service: example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - ../dist/index.js

custom:
  assumeRole:
    roleArn: arn:aws:iam::012345678901:role/your-role-name
    externalId: my-external-id
    roleSessionName: serverless-framework-deployment

functions:
  hello:
    handler: handler.hello
